[[normaliz]]
arch = "aarch64"
git-tree-sha1 = "53be0f79e4a839536562639e02c64c8f09391ed3"
os = "macos"

    [[normaliz.download]]
    sha256 = "cf6efc90fc26d376fec244ef906a4999e640478d36cfb905f66aa0b58b9c9f04"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.aarch64-apple-darwin.tar.gz"
[[normaliz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0263bd7bdefa0c4e3ddf0edf6508781f45a7145e"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "2cb0ee8c078daa9ce11fe59edd52c81b67bd1b387f8bbf472f393be246066180"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.aarch64-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da74d01fc4a46afb02392c415c68a291acf8cb0e"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "c1a640e8adf01ee7f632fcd8b09125f229ac6c4e9f936322f5fb87e7958d579d"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.aarch64-linux-musl-cxx11.tar.gz"
[[normaliz]]
arch = "aarch64"
git-tree-sha1 = "a55096749f3eba888605266a5891d05bce55eb08"
os = "freebsd"

    [[normaliz.download]]
    sha256 = "398dc29c85a95473f43a58e41209c8a47c692ded7ec55b773fee064bd441f4af"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.aarch64-unknown-freebsd.tar.gz"
[[normaliz]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d30a2a700a741cc3c4cf7f1fb1e0a6dc80692f1"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "281e5194599192dcf7d59eda5531c95051f518d883b472e3a84324f89203efa3"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[normaliz]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "122a526c0e229621e47ee09f2aa1f08ca524a3ba"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "6b7b82182c7cb53beb377b655a713faf471de737a67882af55f5893ad14abf5f"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.armv6l-linux-musleabihf-cxx11.tar.gz"
[[normaliz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a9a5e9bc71001482972220934badf71e98738ef"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "4cbd150f46c894e776360286b848a4f37109276369235f303caa2b58eb91dfb9"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[normaliz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11d92e8ecb419d917788e69e00e3eea3906500be"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "169d7bc329c3a085433399876b1de4454496147c04d89aecc34447c0a92e9068"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.armv7l-linux-musleabihf-cxx11.tar.gz"
[[normaliz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf52120b48555f715da1c6b925617be5add66d15"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "f6978dd6481929ce3911864935cf4f056d5fc80c7cd28ff984ff64555e9b3415"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.i686-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56b4e4e17a0c544e98e0aceedca89a261a3d2073"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "83a4ba9be8193e06d6e7ed095ce7dde4857618d8aa9afdc8679c3834ff92cfc6"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.i686-linux-musl-cxx11.tar.gz"
[[normaliz]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dddcd7b389ee9467eafad7b5708f66626084934c"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "b2833e74b42863590b02d579dc1845553f9a58a1a9b43d4802585677a19426ab"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.powerpc64le-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75eb929c0817013967617f4dc17760db0fc1fad0"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "c1ec7f6bd7e3fa1ade0639ab9d0df901dd452ba4afd6b3883550c24d7f603230"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.riscv64-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "x86_64"
git-tree-sha1 = "02d6e0b4d3fa9537531d8494a0d473a5c5216332"
os = "macos"

    [[normaliz.download]]
    sha256 = "9d88789f5dab31e7e24e7019ce32ed1ded8324705b738fe5fb307ae92fc2f747"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.x86_64-apple-darwin.tar.gz"
[[normaliz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8c51037eba722b375fb82c342b8f0e75ac99c63"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "e453389949c82846f3c6ff53979f690c04de688d355f58103178fe49f146d2fc"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.x86_64-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a39a845c7fa43cea7e3b8dd0ddec6958ceec81a"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "36781f045151c47dfe37a582cdc76f667f5e9c945cdb5f7ebbde9a58e60dea78"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.x86_64-linux-musl-cxx11.tar.gz"
[[normaliz]]
arch = "x86_64"
git-tree-sha1 = "ae8736496a9d95c544af958b145da1120a5bf7f3"
os = "freebsd"

    [[normaliz.download]]
    sha256 = "e01b0668f89b50a3c9358113615382bb3dd1ce06ac8d2ff191d4822903aae5c4"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1001.503+0/normaliz.v300.1001.503.x86_64-unknown-freebsd.tar.gz"
